### PR TITLE
Rk/subtutorials

### PR DESCRIPTION
**Pull request by kliegl**
I have drafted a tutorial for contrast specifications. Feel free to disagree.

### CODE REVIEW

**Comment by kliegl** [comment]
@kleinschmidt This might be of interest to you, too. It represents one idea of what could evolve into tutorial paper by Kleinschmidt et al. 

I know we talked about this before and I think the answer was "no", but anyway:  Is there a way to provide labels at least for contrasts constructed with `HypothesisCoding`?  I think the automatically provided labels are quite confusing, especially in a context like this one where we try to compare across different contrast specifications. Perhaps take a look at the examples here. I also would much prefer the `MASS::contr.sdif()`-labels for `SeqDiffCoding`, but if labeling is available for `HypothesisCoding` I could just use this one instead of the canned ones, if I feel there is a need for different labeling of contrasts.

Of course, these are minor gripes. I am still in awe of everything that has been accomplished here.

**Review by dmbates — COMMENTED** [review]
- Thank you for deleting the .Rproj file
- Some of the issues with the levels of `Test` are resolved in the not-yet-released commit to the Arrow.jl package https://github.com/JuliaData/Arrow.jl/pull/164
- If you want to try that version, run julia in the notebooks subdirectory and add the package as the URL https://github.com/JuliaData/Arrow.jl
- I think that the `StatsBase` package may be unnecessary

**Comment by kliegl** [comment]
A) With arrow from github factors maintain their levels. 

B) I extended the contrast tutorial by including for SeqDiffCoding
1.  sex and its interactions with test contrasts, 
2. (age - 8.5) and its interactions with test contrasts
3.  sex x (age - 8.5) and its interactions with test contrasts

This allows us to introduce how contrasts interact with a factor and a covariate in the fixed effect part. This was also the FE-model used in the paper.  For  HelmertCoding and HypothesisCoding I use only the final FE model; also for the final topics.

**Comment by kliegl** [comment]
Ok, I am done with what I would include in the tutorial for contrast coding for now. Of course, the text can and will still be improved (i.e., referring to the Figure when describing results; adding a figure caption). 

I assume eventually we will be able to generate figures directly from the data. For now, I uploaded the three figures that are also in the Fühner et al. paper into a figures folder on the repo.  I like the selection because each figure relates to one of the three random factors. So they may come in handy for other tutorials as well. 

In agreement with Doug, I also think we should shorten and work with simpler LMMs in the current MixedModelsTutorial notebook to illustrate incremental model building and basic MixedModels.jl commands. I could draft this, but perhaps @dmbates prefers to do it himself?  

I will also work on a tutorial about MixedModels.PCA, but not today. I can again use these data, but I also have another nice data set from psycholinguistics where I used MixedModels.PCA with very good results. In both cases the loadings are interpretable and make a lot of sense. It might actually be interesting to compare the solution we get here with one coming estimated with structural equation model. In my mind, this could be used in an Alday et al. paper.

**Comment by kliegl** [comment]
Actually, I had too much fun with Pluto. So I drafted a MixedModelsTutorial_basics.jl notebook. This works really well, I must say. Runs through very smoothly and could be a good reference to go for commands. 

In general, it is easy to see how one can  quickly whip up a collection of such tutorials.  Perhaps it is time to add some of the fancy shiny-like features for interactive model exploration.

**Comment by dmbates** [comment]
@kliegl I'm glad that you are enjoying using Pluto.  I look forward to preparing these tutorials.

**Comment by dmbates** [comment]
@kliegl Could you add the figures directory and I will attempt to create the plots in Julia using AlgebraOfGraphics.jl?

**Comment by kliegl** [comment]
Sorry, just noticed that the figures are still missing

**Comment by kliegl** [comment]
That sounds great. I just noticed that the figures were missing. How do I create a figures directory?

**Comment by dmbates** [comment]
I thought that you had the figures directory in your copy of the repository.  If so you just

git add figures/Figure_2.png

etc. then git commit and git push.  Or you can do the whole thing withing VS Code.

**Comment by kliegl** [comment]
I am not sure exactly how I did it, but the folder and the three figures are there. Currently only the #2 is used. Sorry for the numbering; they correspond to the one used in the paper.

**Comment by dmbates** [comment]
I assume the ages just rounded to the nearest 0.1 year to produce the horizontal axis.  Is that correct?

**Comment by kliegl** [comment]
That's correct. The line was fit to continuous age, but I always like to add some observed means.

**Comment by kliegl** [comment]
Here is the figure caption. Should be in the notebooks, too, now.

Performance differences between 8.0 und 9.0 years by sex in the five physical fitness tests presented as z-transformed data computed separately for each test. Endurance = cardiorespiratory endurance (i.e., 6 min run test), Coordination = star run test, Speed = 20-m linear sprint test, PowerLOW = power of lower limbs (i.e., standing long jump test), PowerUP = power of upper limbs (i.e., ball push test), SD = standard deviation. Points are binned observed child means; lines are simple regression fits to the observations; 95% confidence intervals for means ≈ 0.05 are not visible.

**Comment by kliegl** [comment]
I will try to  insert a link to the Emotikon project website -- all in German, but there are buttons to show short videos of each task.
[emotikon_tests](https://www.uni-potsdam.de/de/emotikon/projekt/methodik )
 
Pluto can handle such links nicely -- at least I saw one somewhere.

**Comment by dmbates** [comment]
It may not be in this pull request but you mentioned not storing the `Test` and other categorical columns as `String`s.  In fact they are stored as the `Arrow.DictEncoded` type which is like a `factor` in R.
```julia
julia> dat = Arrow.Table("./data/fggk21.arrow");

julia> show(keys(dat))
[:Cohort, :District, :BU, :School, :Child, :Sex, :age, :Test, :score, :zScore]
julia> typeof(dat.Test)
Arrow.DictEncoded{String, Int8, Arrow.List{String, Int32, Vector{UInt8}}}
```
In some ways I think the most concise description of the contents of an arrow file is through the pyarrow package for Python.
```julia
julia> using PyCall

julia> feather = pyimport("pyarrow.feather")
PyObject <module 'pyarrow.feather' from '/home/bates/.julia/conda/3/lib/python3.8/site-packages/pyarrow/feather.py'>

julia> feather.read_table("./data/fggk21.arrow")
PyObject pyarrow.Table
Cohort: dictionary<values=string, indices=int8, ordered=0> not null
District: dictionary<values=string, indices=int8, ordered=0> not null
BU: dictionary<values=string, indices=int8, ordered=0> not null
School: dictionary<values=string, indices=int16, ordered=0> not null
Child: dictionary<values=string, indices=int32, ordered=0> not null
Sex: dictionary<values=string, indices=int8, ordered=0> not null
age: double not null
Test: dictionary<values=string, indices=int8, ordered=0> not null
score: double not null
zScore: double not null
```

**Comment by kliegl** [comment]
Thank you for the explanation! Yes, after using the github version, I realized that these are not the usual strings, but I was still wondering. 

It is listed as an issue and you proposed to keep it open. I think I can close it again. Right?

**Comment by dmbates** [comment]
Sure, please close the issue.

**Comment by dmbates** [comment]
I have managed to produce something like Figure_2.png using the AlgebraOfGraphics.jl package.  As you can imagine it goes through several stages.  I will make a short notebook about it then we can see if we want to merge that block into the "basics" notebook.

**Comment by kliegl** [comment]
😊👍

**Comment by kliegl** [comment]
Ok. I can run the notebook and see the graph. Impressive.

**Comment by dmbates** [comment]
Do the .Rmd files on the osf.io site describe how the rounded age was calculated?  As you see, I used rounding to the nearest 0.1 years which gave values from 8.0 to 9.1  The horizontal axis on Figure_2.png just goes to 9.0

In the caption you say, "lines are simple regression fits to the observations".  Are "the observations" the per-student observations of `zScore` or the `zScore_mean` for each of the groups?

Also, do you want to pursue why the zscore calculation in Julia gives different results from those in the table from R?

By the way, you can read the arrow file created in Julia into R.
```R
R> library(arrow)
┌ Warning: RCall.jl: 
│ Attaching package: ‘arrow’
│ 
│ The following object is masked from ‘package:utils’:
│ 
│     timestamp
│ 
└ @ RCall ~/.julia/packages/RCall/eRsxl/src/io.jl:160

R> library(tibble)

R> glimpse(read_feather("./data/fggk21.arrow"))
Rows: 525,126
Columns: 10
$ Cohort   <fct> 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2…
$ District <fct> SPN, SPN, SPN, SPN, SPN, SPN, SPN, SPN, SPN, SPN, SPN, SPN, S…
$ BU       <fct> U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U…
$ School   <fct> S100043, S100043, S100043, S100043, S100043, S100043, S100043…
$ Child    <fct> C000304, C000304, C000304, C000304, C000304, C000305, C000305…
$ Sex      <fct> female, female, female, female, female, female, female, femal…
$ age      <dbl> 8.125941, 8.125941, 8.125941, 8.125941, 8.125941, 8.295688, 8…
$ Test     <fct> S20_r, BPT, SLJ, Star_r, Run, S20_r, BPT, SLJ, Star_r, Run, S…
$ score    <dbl> 4.166667, 2.400000, 91.000000, 1.616254, 840.000000, 4.081633…
$ zScore   <dbl> -0.83591538, -1.84859468, -1.75634651, -1.44326168, -1.043644…
```

**Comment by dmbates** [comment]
@kliegl Let me know how you would like to proceed.  No rush, I'm back working on the MixedModels.jl repository.

**Comment by kliegl** [comment]
> Do the .Rmd files on the osf.io site describe how the rounded age was calculated? As you see, I used rounding to the nearest 0.1 years which gave values from 8.0 to 9.1 The horizontal axis on Figure_2.png just goes to 9.0
+ Yes, this is the code that generated the Figure_2.png.  T
+ The restriction of 8.00 years to 8.99 years refers to the legal keydate (30 Sept) for school enrollment. This ensures that that our sample does not include early or late enrolling children. Children's age , however,  is computed as the difference between testdate (a couple of months into the school year, but varying between children, schools, and cohorts) and birthdate (15-month-year for reasons of privacy protection).  As a consequence, the age may be slightly below 8 or slightly above 9 years.

> In the caption you say, "lines are simple regression fits to the observations". Are "the observations" the per-student observations of `zScore` or the `zScore_mean` for each of the groups?
Yes, the lines were fit to the observations (within panels they are all independent). I use the binned means mostly for aesthetic reasons. 

> Also, do you want to pursue why the zscore calculation in Julia gives different results from those in the table from R?
The reason is that after the final standardization a +/- 3 SD criterion was applied for removal of scores. I did not re-standardize. Therefore, your standardization is computed on a reduced set of observations without outliers; my standardization still has some influence from the excluded scores.  This is described in the paper: "Finally, we applied a +/-3 SD criterion to individual test scores which led to the exclusion of another 2,175 children (2%)."   I think this is a defensible strategy, right?

> By the way, you can read the arrow file created in Julia into R.
I will move the arrows file into the OSF repo.  Thanks!

**Comment by kliegl** [comment]
> Let me know how you would like to proceed. No rush, I'm back working on the MixedModels.jl repository.
I am very happy with the Pluto notebooks.  I think the current ones have about the right amount of information, possibly even already too much. I could contribute to at least the following two sets:

Set 1: additional LMM stuff, e.g.,
+  on 0 + Test / (Sex + (age - 8.5)) + ...
+  on the  distinction between CPs based on effects and scores
+  on fulldummy() 
+ on MixedModels.PCA(). 
+ observation-level residuals
+ parametric bootstrapping / profiling of model parameters

Set 2: Conditional Modes / shrinkage / borrowing strength (see Figure_4.png)
+ Caterpillar plots
+ Bivariate shrinkage plots
+ group-level residuals

Some of those bullet points could be combined into one tutorial, possibly.  It would also be nice to explore the interactive options (shiny-like) Pluto offers. Simple start would be to have a slider that allows one to select the order of a polynomial trend or the the span for a smooth.  Could one actually also pass parameters to sample a smaller number of subjects before fitting a model?  I have a shiny app for shrinkage simulation. Perhaps this could be ported to Pluto. Stuff like this. 

But what do you think? 
+ Do you agree when the general outline of the first two tutorials? 
+ Could you, for example, put more text into Glossary section of the Tutorial_basics?

I am working on these tutorials also with an eye towards converting them into papers. You also drafted quite a bit of text already for a paper.  Assuming we agree on a way forward as suggested above, should this be brought into a compatbile format?  Not sure whether this could work.

**Pull request merged**
