### PR TITLE
Switch to Arrow for binary data storage

### PR DESCRIPTION
**Pull request by dmbates**
- Minor changes in the `sleepstudy` notebook
- Switch to Arrow for binary data storage in `MixedModelsTutorial` notebook
- `MixedModelsTutorial` takes much too long to load - we should come up with a way of saving/loading the parameter estimates.
- I botched up the editing of the `MixedModelsTutorial` notebook which is why all the chunk UUID's have changed.

### CODE REVIEW

**Comment by kliegl** [comment]
If I merge a pull request, do I also delete the branch -- or this up to the creator of the branch?

**Comment by dmbates** [comment]
Either one is okay.  I will delete the branch now.

Generally we leave a PR up for discussion for a day or two before merging.  One thing I didn't mention about this PR is that I changed the contrasts for the fixed-effects factors to `HelmertCoding()` and that seems to have caused convergence to be much slower.  Also it will change the meaning of any models using `zerocorr` random-effects terms.  We need to think about what to say regarding the `Test` factor and contrasts for it.  I'll open an issue where we can discuss this.

**Comment by kliegl** [comment]
I think I anticipated these issues in the contrast tutorial that's up for a pull request.

**Comment by dmbates** [comment]
@kliegl Yes, I saw that.  I am looking at the contrast tutorial now.

**Pull request merged**
